# Generated by Django 4.2.7 on 2023-11-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_slider_alter_services_image_alter_services_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=500, null=True, upload_to='staff_img/')),
                ('name', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=50)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
