# Generated by Django 4.2.7 on 2023-11-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='facebook_link',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='instagram_link',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='linkedin_link',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='twitter_link',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
    ]
