# Generated by Django 4.2.7 on 2023-11-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_staff_facebook_link_alter_staff_instagram_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=500, null=True, upload_to='category_rooms_img/')),
                ('category_name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=155)),
                ('foot', models.IntegerField(max_length=3)),
                ('people_Capacity', models.IntegerField(max_length=3)),
                ('room_price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='posicion',
            new_name='position',
        ),
    ]
