# Generated by Django 4.2.7 on 2023-11-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_category_rooms_rename_posicion_staff_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.BigIntegerField(max_length=12)),
                ('image', models.ImageField(default=None, max_length=500, null=True, upload_to='user_img/')),
                ('address', models.TextField()),
                ('pincode', models.BigIntegerField(max_length=6)),
                ('birth', models.DateField()),
                ('password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
            ],
        ),
    ]
