# Generated by Django 4.2.7 on 2024-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_No', models.IntegerField(max_length=5)),
                ('image', models.FileField(max_length=500, upload_to='room_img/')),
                ('room_name', models.CharField(max_length=50)),
                ('aboults', models.IntegerField(max_length=20)),
                ('children', models.IntegerField(max_length=20)),
                ('room_price', models.IntegerField(max_length=5)),
            ],
        ),
    ]
